### PR TITLE
delete/update post - issue #123

### PR DESCRIPTION
**Pull request by jk1dd**
this addresses issue #123 

I had to change AWS configuration to my own bucket to get it working locally. I also added some configuration to get capybara working correctly, specifically for a user to sign in. 

A user can delete a post, and update it - but only update the caption.

Let me know of any questions or comments!

### CODE REVIEW

**Comment by kalimar** [comment]
Sweet work @jk1dd - This is really helpful. I think the next step is for some styling and perhaps a confirmation button for the delete action. Can all users modify all posts @jk1dd?
Any thoughts @Pratt0923 @maebeale? 

Here are the places I think need some styling. These would be new issues for anyone to pick up.
screen shot 2017-07-30 at 8 41 31 am
screen shot 2017-07-30 at 8 41 17 am

**Comment by jk1dd** [comment]
@kalimar currently, all users can modify all posts! i can absolutely add some logic to restrict that to the post creator, if that's the way you'd like to go.

**Comment by kalimar** [comment]
hi @jk1dd - thanks for the response. I'll leave that decision to our awesome product owners: @Pratt0923 and @maebeale . Thoughts?

**Comment by maebeale** [comment]
thanks @jk1dd ! 

we do want all users to be able to add/edit tags on existing posts, but not necessarily be able to edit the photo or title.

we will need some admin-type permissions so they can hide a post deemed problematic, so were leaving all posts editable until we could add the permissions. if you're up for adding the permissions and then making posts only editable by the creator and any admin, that'd be amazing!!!

**Pull request merged**
