### PR TITLE
Action mailer

### PR DESCRIPTION
**Pull request by aceofbassgreg**
## Context

This PR doesn't have much to do with `ActionMailer` after all! 

What it DOES do is, creates `EmailTemplate` MVC so users can create email templates. Once this gets merged in, we'll add more controller actions (editing an email template) and additional functionality (setting up workflow to use template to email users).

If you want me to add tests before approving this PR that's totally fair.

### CODE REVIEW

**Review by michaelbyrd — COMMENTED** [review]
I'd remove app/assets/javascripts/email_templates.coffee,
app/assets/stylesheets/email_templates.scss,
app/helpers/email_templates_helper.rb,
spec/helpers/email_templates_helper_spec.rb

**Review by michaelbyrd — COMMENTED** [review]
<% if @post.errors.any? %>
  <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

**Comment by aceofbassgreg** [comment]
@michaelbyrd updated with your suggestion. G2G?

**Review by michaelbyrd — APPROVED** [review]
lgtm

**Pull request merged**
